### ISSUE TITLE
Open source license for SwiftConnect

### ISSUE THREAD

**Issue by girivs82** [wenyuzhao/SwiftConnect#2]
Hi,

I currently have a heavily modified fork of the SwiftConnect that I use which adds SAMLv2 authentication support to AnyConnect along with a number of other changes. I'd like to contribute it back to your repository, but the changes are extensive, so will require some co-ordination to get my changes in.

I noticed that you do not have a open source license specified in your project. Could we agree on one and add a LICENSE file to the repo?  That will help add it to the EULA if/when I distribute the app as a binary. I guess my preference is a modified BSD or Apache license, but entirely up to you.

Shankar

**Comment by girivs82** [comment]
Any updates on this? Bumping in case this was missed.

**Comment by wenyuzhao** [comment]
Sorry I haven't had time to work on this project recently. I just added an MIT license. Thanks:)

**Comment by girivs82** [comment]
Thanks!
